import Link from 'next/link';

export default function Home() {
  return (
    <main className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-2xl mx-auto">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">
          hazo_logs Test Application
        </h1>

        <div className="bg-white shadow rounded-lg p-6 space-y-6">
          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-2">
              Log Viewer
            </h2>
            <p className="text-gray-600 mb-4">
              View and filter logs generated by the test application.
            </p>
            <Link
              href="/logs"
              className="inline-block px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition"
            >
              Open Log Viewer
            </Link>
          </div>

          <hr />

          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-2">
              Generate Test Logs
            </h2>
            <p className="text-gray-600 mb-4">
              Run the following command to generate test logs from different packages:
            </p>
            <pre className="bg-gray-100 p-3 rounded-md text-sm overflow-x-auto">
              npm run generate-logs
            </pre>
          </div>

          <hr />

          <div>
            <h2 className="text-xl font-semibold text-gray-800 mb-2">
              API Endpoints
            </h2>
            <ul className="text-gray-600 space-y-2">
              <li>
                <code className="bg-gray-100 px-2 py-1 rounded text-sm">
                  GET /api/logs
                </code>
                <span className="ml-2">- Query logs with filters</span>
              </li>
              <li>
                <code className="bg-gray-100 px-2 py-1 rounded text-sm">
                  GET /api/logs?action=dates
                </code>
                <span className="ml-2">- Get available log dates</span>
              </li>
              <li>
                <code className="bg-gray-100 px-2 py-1 rounded text-sm">
                  GET /api/logs?action=packages
                </code>
                <span className="ml-2">- Get package names</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </main>
  );
}
